package com.stockpro.reportservice.service;

import com.stockpro.reportservice.dto.request.ReportFilterRequest;
import com.stockpro.reportservice.dto.response.AlertSummaryReportResponse;
import com.stockpro.reportservice.dto.response.DeadStockResponse;
import com.stockpro.reportservice.dto.response.ExecutiveDashboardResponse;
import com.stockpro.reportservice.dto.response.InventorySnapshotResponse;
import com.stockpro.reportservice.dto.response.InventoryTurnoverResponse;
import com.stockpro.reportservice.dto.response.InventoryValuationResponse;
import com.stockpro.reportservice.dto.response.LowStockReportItem;
import com.stockpro.reportservice.dto.response.OverstockReportItem;
import com.stockpro.reportservice.dto.response.PaymentSummaryReportResponse;
import com.stockpro.reportservice.dto.response.ProductValuationItem;
import com.stockpro.reportservice.dto.response.PurchaseSummaryResponse;
import com.stockpro.reportservice.dto.response.SlowMovingProductResponse;
import com.stockpro.reportservice.dto.response.StockMovementReportItem;
import com.stockpro.reportservice.dto.response.StockSummaryResponse;
import com.stockpro.reportservice.dto.response.SupplierPerformanceReportResponse;
import com.stockpro.reportservice.dto.response.TopMovingProductResponse;
import com.stockpro.reportservice.dto.response.WarehouseValuationItem;
import com.stockpro.reportservice.enums.ExportFormat;
import java.time.LocalDate;
import java.util.List;
import org.springframework.data.domain.Page;

public interface ReportService {
    InventoryValuationResponse getInventoryValuation(ReportFilterRequest request);
    StockSummaryResponse getStockSummary(ReportFilterRequest request);
    Page<ProductValuationItem> getProductStockReport(ReportFilterRequest request);
    Page<WarehouseValuationItem> getWarehouseStockReport(ReportFilterRequest request);
    Page<LowStockReportItem> getLowStockReport(ReportFilterRequest request);
    Page<OverstockReportItem> getOverstockReport(ReportFilterRequest request);
    Page<StockMovementReportItem> getStockMovementReport(ReportFilterRequest request);
    List<InventoryTurnoverResponse> getInventoryTurnoverReport(ReportFilterRequest request);
    List<TopMovingProductResponse> getTopMovingProducts(ReportFilterRequest request);
    List<SlowMovingProductResponse> getSlowMovingProducts(ReportFilterRequest request);
    List<DeadStockResponse> getDeadStockReport(ReportFilterRequest request);
    PurchaseSummaryResponse getPurchaseSummary(ReportFilterRequest request);
    SupplierPerformanceReportResponse getSupplierPerformance(Long supplierId, ReportFilterRequest request);
    Page<SupplierPerformanceReportResponse> getSupplierPerformanceReport(ReportFilterRequest request);
    PaymentSummaryReportResponse getPaymentSummary(ReportFilterRequest request);
    AlertSummaryReportResponse getAlertSummary(ReportFilterRequest request);
    ExecutiveDashboardResponse getExecutiveDashboard();
    ExecutiveDashboardResponse getRoleDashboard(String role, Long userId);
    void createDailyInventorySnapshot();
    void createInventorySnapshotForDate(LocalDate date);
    Page<InventorySnapshotResponse> getInventorySnapshots(LocalDate date, int page, int size);
    List<InventorySnapshotResponse> getSnapshotTrend(Long productId, Long warehouseId, LocalDate fromDate, LocalDate toDate);
    byte[] exportInventoryValuation(ReportFilterRequest request, ExportFormat format);
    byte[] exportStockMovementReport(ReportFilterRequest request, ExportFormat format);
    byte[] exportPurchaseSummary(ReportFilterRequest request, ExportFormat format);
    byte[] exportSupplierPerformance(ReportFilterRequest request, ExportFormat format);
    byte[] exportExecutiveDashboard(ExportFormat format);
}
