server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: AUTH-SERVICE

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - openid
              - profile
              - email

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    home-page-url: http://localhost:${server.port}/
    status-page-url: http://localhost:${server.port}/actuator/info
    health-check-url: http://localhost:${server.port}/actuator/health

# JWT config
jwt:
  secret: ${JWT_SECRET}
  expiration: 28800000
  refresh-expiration: 604800000

logging:
  level:
    com.stockpro: DEBUG
  file:
    name: logs/auth-service.log

app:
  frontend-url: ${FRONTEND_URL}
  otp:
    expiry-minutes: ${OTP_EXPIRY_MINUTES:5}
  mail:
    from: ${MAIL_FROM:surajkr1122003@gmail.com}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
