package com.stockpro.purchaseservice.enums;

public enum PurchaseEventType {
    PURCHASE_ORDER_CREATED,
    PURCHASE_ORDER_UPDATED,
    PURCHASE_ORDER_SUBMITTED,
    PURCHASE_ORDER_APPROVED,
    PURCHASE_ORDER_REJECTED,
    PURCHASE_ORDER_CANCELLED,
    PURCHASE_ORDER_PARTIALLY_RECEIVED,
    PURCHASE_ORDER_FULLY_RECEIVED,
    PURCHASE_ORDER_OVERDUE,
    PURCHASE_ORDER_PENDING_APPROVAL
}
