ALTER TABLE alerts
MODIFY COLUMN type VARCHAR(50) NOT NULL,
MODIFY COLUMN severity VARCHAR(20) NOT NULL,
MODIFY COLUMN status VARCHAR(20) NOT NULL,
MODIFY COLUMN channel VARCHAR(20) NOT NULL;

UPDATE alerts
SET type = 'PO_APPROVAL_PENDING'
WHERE type = 'PO_PENDING_APPROVAL';

UPDATE alerts
SET type = 'PO_OVERDUE_RECEIPT'
WHERE type = 'OVERDUE_RECEIPT';

UPDATE alerts
SET type = 'MOVEMENT_ANOMALY'
WHERE type = 'STOCK_MOVEMENT';

UPDATE alerts
SET type = 'SYSTEM_BROADCAST'
WHERE type = 'SYSTEM_NOTIFICATION';

UPDATE alerts
SET type = 'GENERAL'
WHERE type = 'USER_ACTION_REQUIRED';
