ALTER TABLE alerts
MODIFY COLUMN type VARCHAR(50) NOT NULL,
MODIFY COLUMN severity VARCHAR(30) NOT NULL,
MODIFY COLUMN status VARCHAR(30) NOT NULL,
MODIFY COLUMN channel VARCHAR(30) NULL,
MODIFY COLUMN recipient_role VARCHAR(50) NULL,
MODIFY COLUMN is_archived BIT(1) NOT NULL DEFAULT b'0';

UPDATE alerts
SET is_archived = b'0'
WHERE is_archived IS NULL;
