package com.stockpro.paymentservice.enums;

public enum PaymentEventType {
    PAYMENT_CREATED,
    PAYMENT_UPDATED,
    PAYMENT_SUBMITTED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    PAYMENT_CANCELLED,
    PAYMENT_PARTIALLY_PAID,
    PAYMENT_PAID,
    PAYMENT_REVERSED
}
