server:
  port: 8089

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${PAYMENT_DB_USERNAME}
    password: ${PAYMENT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      use-suffix-pattern: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    com.stockpro: DEBUG
  file:
    name: logs/payment-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true

jwt:
  secret: ${JWT_SECRET}

purchase-service:
  base-url: ${PURCHASE_SERVICE_BASE_URL}

supplier-service:
  base-url: ${SUPPLIER_SERVICE_BASE_URL}

stockpro:
  rabbitmq:
    payment:
      exchange: ${PAYMENT_RABBITMQ_EXCHANGE:stockpro.payment.exchange}
      events-queue: ${PAYMENT_EVENTS_QUEUE:stockpro.payment.events.queue}
      report-queue: ${PAYMENT_REPORT_QUEUE:stockpro.payment.report.queue}
      alert-queue: ${PAYMENT_ALERT_QUEUE:stockpro.payment.alert.queue}
      purchase-queue: ${PAYMENT_PURCHASE_QUEUE:stockpro.payment.purchase.queue}
