package com.stockpro.reportservice.enums;

public enum ReportType {
    INVENTORY_VALUATION,
    STOCK_SUMMARY,
    WAREHOUSE_STOCK,
    PRODUCT_STOCK,
    LOW_STOCK,
    OVERSTOCK,
    STOCK_MOVEMENT,
    INVENTORY_TURNOVER,
    TOP_MOVING_PRODUCTS,
    SLOW_MOVING_PRODUCTS,
    DEAD_STOCK,
    PURCHASE_SUMMARY,
    SUPPLIER_PERFORMANCE,
    PAYMENT_SUMMARY,
    ALERT_SUMMARY,
    EXECUTIVE_DASHBOARD
}
