package com.stockpro.alertservice.enums;

public enum AlertType {
    LOW_STOCK,
    OVERSTOCK,
    PO_APPROVAL_PENDING,
    PO_APPROVED,
    PO_REJECTED,
    PO_OVERDUE_RECEIPT,
    PO_RECEIVED,
    SUPPLIER_DEACTIVATED,
    SUPPLIER_BLACKLISTED,
    MOVEMENT_ANOMALY,
    STOCK_TRANSFER,
    SYSTEM_BROADCAST,
    REPORT_READY,
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    GENERAL
}
